name: Deployment

on:
  workflow_dispatch:
    inputs:
      service_a:
        description: 'Deploy service_a'
        required: true
        type: string
      service_b:
        description: 'Deploy service_b'
        required: true
        type: string

jobs:
  deploy-stg-service-a:
    runs-on: ubuntu-latest
    environment: stg
    if: ${{ inputs.service_a == 'true' }}
    concurrency:
      group: stg-service-a
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy auth-service
        run: echo "Deploying to stg service-a on ${{ github.ref_name }}"

  deploy-prd-service-a:
    needs: deploy-stg-service-a
    runs-on: ubuntu-latest
    environment: prd
    concurrency:
      group: prd-service-a
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy service-a
        run: echo "Deploying to prod service-a on ${{ github.ref_name }}"

  deploy-stg-service-b:
    runs-on: ubuntu-latest
    environment: stg
    if: ${{ inputs.service-b == 'true' }}
    concurrency:
      group: stg-service-b
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy service-b
        run: echo "Deploying to stg service-b on ${{ github.ref_name }}"

  deploy-prd-service-b:
    needs: deploy-stg-service-b
    runs-on: ubuntu-latest
    environment: prd
    concurrency:
      group: prd-service-b
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy service-b
        run: echo "Deploying to prod service-b on ${{ github.ref_name }}"
